// <auto-generated />
using System;
using CREA.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CREA.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CREA.Domain.Entities.Anexo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AnexoId");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("CaminhoArquivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("NomeArquivoOriginal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ObraId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RelatoVisitaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoArquivo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ObraId");

                    b.HasIndex("RelatoVisitaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Anexos");
                });

            modelBuilder.Entity("CREA.Domain.Entities.Assinatura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AssinaturaId");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataAssinatura")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dispositivo")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<Guid>("EntidadeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HashAssinatura")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ImagemAssinatura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAssinante")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Navegador")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("SistemaOperacional")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("TipoAssinante")
                        .HasColumnType("int");

                    b.Property<int>("TipoEntidade")
                        .HasColumnType("int");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("TipoEntidade", "EntidadeId", "TipoAssinante")
                        .IsUnique();

                    b.ToTable("Assinaturas");
                });

            modelBuilder.Entity("CREA.Domain.Entities.LogAuditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("LogAuditoriaId");

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("DadosAntigos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DadosNovos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataAcao")
                        .HasColumnType("datetime2");

                    b.Property<string>("EnderecoIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Entidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EntidadeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("LogsAuditoria");
                });

            modelBuilder.Entity("CREA.Domain.Entities.Obra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ObraId");

                    b.Property<decimal?>("AreaAmpliar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AreaConstruir")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AreaReformar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AreaRegularizar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AreaTotalEdificada")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("AtividadeTecnica")
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataPrevisaoTermino")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DirecaoTecnica")
                        .HasColumnType("bit");

                    b.Property<string>("Empresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NumeroArt")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumeroCaderneta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroRT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProfissionalResponsavelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProprietarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TipoEdificacao")
                        .HasColumnType("int");

                    b.Property<int>("TipoObra")
                        .HasColumnType("int");

                    b.Property<Guid>("UsuarioCriadorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ValorRecibo")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProfissionalResponsavelId");

                    b.HasIndex("ProprietarioId");

                    b.HasIndex("UsuarioCriadorId");

                    b.ToTable("Obras");
                });

            modelBuilder.Entity("CREA.Domain.Entities.Profissional", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ProfissionalId");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Empresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Especialidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NumeroRegistro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TipoRegistro")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("NumeroRegistro")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("Profissionais");
                });

            modelBuilder.Entity("CREA.Domain.Entities.Proprietario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ProprietarioId");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique()
                        .HasFilter("[UsuarioId] IS NOT NULL");

                    b.ToTable("Proprietarios");
                });

            modelBuilder.Entity("CREA.Domain.Entities.RelatoVisita", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RelatoVisitaId");

                    b.Property<bool>("Alvenarias")
                        .HasColumnType("bit");

                    b.Property<string>("Atividades")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Cobertura")
                        .HasColumnType("bit");

                    b.Property<string>("CondicaoClimatica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("DecisoesTecnicas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EquipePresente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsquadriasInstalacoesEletricasHidraulicas")
                        .HasColumnType("bit");

                    b.Property<bool>("Fundacao")
                        .HasColumnType("bit");

                    b.Property<int>("NumeroSequencial")
                        .HasColumnType("int");

                    b.Property<Guid>("ObraId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Pintura")
                        .HasColumnType("bit");

                    b.Property<int?>("PosicaoObra")
                        .HasColumnType("int");

                    b.Property<bool>("RevestimentoForroParePiso")
                        .HasColumnType("bit");

                    b.Property<bool>("ServicosComplementares")
                        .HasColumnType("bit");

                    b.Property<bool>("ServicosPreliminar")
                        .HasColumnType("bit");

                    b.Property<bool>("Superestrutura")
                        .HasColumnType("bit");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ObraId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("RelatosVisita");
                });

            modelBuilder.Entity("CREA.Domain.Entities.TermoConclusao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TermoConclusaoId");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataConclusao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataDeclaracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeclaracaoTexto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocalDeclaracao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroTermo")
                        .HasColumnType("int");

                    b.Property<Guid>("ObraId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ProfissionalId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ObraId")
                        .IsUnique();

                    b.HasIndex("ProfissionalId");

                    b.ToTable("TermosConclusao");
                });

            modelBuilder.Entity("CREA.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UsuarioId");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("CREA.Domain.Entities.Anexo", b =>
                {
                    b.HasOne("CREA.Domain.Entities.Obra", "Obra")
                        .WithMany("Anexos")
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("CREA.Domain.Entities.RelatoVisita", "RelatoVisita")
                        .WithMany("Anexos")
                        .HasForeignKey("RelatoVisitaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("CREA.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Anexos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Obra");

                    b.Navigation("RelatoVisita");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CREA.Domain.Entities.Assinatura", b =>
                {
                    b.HasOne("CREA.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Assinaturas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CREA.Domain.Entities.Obra", b =>
                {
                    b.HasOne("CREA.Domain.Entities.Profissional", "ProfissionalResponsavel")
                        .WithMany("ObrasComoResponsavel")
                        .HasForeignKey("ProfissionalResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CREA.Domain.Entities.Proprietario", "Proprietario")
                        .WithMany("Obras")
                        .HasForeignKey("ProprietarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CREA.Domain.Entities.Usuario", "UsuarioCriador")
                        .WithMany()
                        .HasForeignKey("UsuarioCriadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProfissionalResponsavel");

                    b.Navigation("Proprietario");

                    b.Navigation("UsuarioCriador");
                });

            modelBuilder.Entity("CREA.Domain.Entities.Profissional", b =>
                {
                    b.HasOne("CREA.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CREA.Domain.Entities.Proprietario", b =>
                {
                    b.HasOne("CREA.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Proprietario")
                        .HasForeignKey("CREA.Domain.Entities.Proprietario", "UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CREA.Domain.Entities.RelatoVisita", b =>
                {
                    b.HasOne("CREA.Domain.Entities.Obra", "Obra")
                        .WithMany("RelatoVisita")
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CREA.Domain.Entities.Usuario", "Usuario")
                        .WithMany("RelatoVisita")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Obra");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CREA.Domain.Entities.TermoConclusao", b =>
                {
                    b.HasOne("CREA.Domain.Entities.Obra", "Obra")
                        .WithOne("TermoConclusao")
                        .HasForeignKey("CREA.Domain.Entities.TermoConclusao", "ObraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CREA.Domain.Entities.Profissional", null)
                        .WithMany("TermosConclusao")
                        .HasForeignKey("ProfissionalId");

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("CREA.Domain.Entities.Obra", b =>
                {
                    b.Navigation("Anexos");

                    b.Navigation("RelatoVisita");

                    b.Navigation("TermoConclusao");
                });

            modelBuilder.Entity("CREA.Domain.Entities.Profissional", b =>
                {
                    b.Navigation("ObrasComoResponsavel");

                    b.Navigation("TermosConclusao");
                });

            modelBuilder.Entity("CREA.Domain.Entities.Proprietario", b =>
                {
                    b.Navigation("Obras");
                });

            modelBuilder.Entity("CREA.Domain.Entities.RelatoVisita", b =>
                {
                    b.Navigation("Anexos");
                });

            modelBuilder.Entity("CREA.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Anexos");

                    b.Navigation("Assinaturas");

                    b.Navigation("Proprietario");

                    b.Navigation("RelatoVisita");
                });
#pragma warning restore 612, 618
        }
    }
}
